service: wayfinder

provider:
  name: aws
  profile: serverless-admin
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  index:
    handler: server/functions/index.handler
    timeout: 120
    events:
      - http: 
          path: walk
          method: get
          cors: true

plugins:
  - serverless-finch

custom:
  client:
    bucketName: wayfinder-site
    distributionFolder: client
    indexDocument: index.html
    errorDocument: index.html
    routingRules:
      - redirect: 
          hostName: "${file(./slsHelpers.js):getApiUrl}.execute-api.${self:provider.region}.amazonaws.com"
          httpRedirectCode: 301
          protocol: https
          replaceKeyPrefixWith: ${self:provider.stage}/walk
        condition:
          keyPrefixEquals: api/walk

# custom:
#     tableName: 'users-table-${self:provider.stage}'

# resources:
#   Resources:
#     UsersDynamoDBTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: userId
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: userId
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:custom.tableName}